name: ddm_gRPC
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc: ^3.0.0
  protobuf: ^2.0.0-nullsafety
  test: ^1.16.8

dev_dependencies:
  build_runner: ^1.12.2
  pedantic: ^1.9.0
